package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "agent", catalog = "bankelmaghrib")
public class Agent implements java.io.Serializable {

	private Integer id;
	private Poste poste;
	private Mesure mesure;
	private String nom;
	private String prenom;
	private String entite;
	private String sexe;

	public Agent() {
	}

	public Agent(Poste poste, Mesure mesure, String nom, String prenom, String entite, String sexe) {
		this.poste = poste;
		this.mesure = mesure;
		this.nom = nom;
		this.prenom = prenom;
		this.entite = entite;
		this.sexe = sexe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poste", nullable = false)
	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mesure", nullable = false)
	public Mesure getMesure() {
		return this.mesure;
	}

	public void setMesure(Mesure mesure) {
		this.mesure = mesure;
	}

	@Column(name = "nom", nullable = false, length = 256)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 256)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "entite", nullable = false, length = 100)
	public String getEntite() {
		return this.entite;
	}

	public void setEntite(String entite) {
		this.entite = entite;
	}

	@Column(name = "sexe", nullable = false, length = 100)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

}
