package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "bankelmaghrib")
public class Article implements java.io.Serializable {

	private String intitule;
	private Categorie categorie;
	private Set<TenueArticle> tenueArticles = new HashSet<TenueArticle>(0);

	public Article() {
	}

	public Article(String intitule, Categorie categorie) {
		this.intitule = intitule;
		this.categorie = categorie;
	}

	public Article(String intitule, Categorie categorie, Set<TenueArticle> tenueArticles) {
		this.intitule = intitule;
		this.categorie = categorie;
		this.tenueArticles = tenueArticles;
	}

	@Id

	@Column(name = "intitule", unique = true, nullable = false, length = 100)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "article")
	public Set<TenueArticle> getTenueArticles() {
		return this.tenueArticles;
	}

	public void setTenueArticles(Set<TenueArticle> tenueArticles) {
		this.tenueArticles = tenueArticles;
	}

}
