package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "bankelmaghrib")
public class Categorie implements java.io.Serializable {

	private String intitule;
	private Set<Article> articles = new HashSet<Article>(0);

	public Categorie() {
	}

	public Categorie(String intitule) {
		this.intitule = intitule;
	}

	public Categorie(String intitule, Set<Article> articles) {
		this.intitule = intitule;
		this.articles = articles;
	}

	@Id

	@Column(name = "intitule", unique = true, nullable = false, length = 100)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
