package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poste generated by hbm2java
 */
@Entity
@Table(name = "poste", catalog = "bankelmaghrib")
public class Poste implements java.io.Serializable {

	private String intitule;
	private Tenue tenue;
	private Set<Agent> agents = new HashSet<Agent>(0);

	public Poste() {
	}

	public Poste(String intitule, Tenue tenue) {
		this.intitule = intitule;
		this.tenue = tenue;
	}

	public Poste(String intitule, Tenue tenue, Set<Agent> agents) {
		this.intitule = intitule;
		this.tenue = tenue;
		this.agents = agents;
	}

	@Id

	@Column(name = "intitule", unique = true, nullable = false, length = 100)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tenue", nullable = false)
	public Tenue getTenue() {
		return this.tenue;
	}

	public void setTenue(Tenue tenue) {
		this.tenue = tenue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poste")
	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = agents;
	}

}
