package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TenueArticle generated by hbm2java
 */
@Entity
@Table(name = "tenue_article", catalog = "bankelmaghrib")
public class TenueArticle implements java.io.Serializable {

	private TenueArticleId id;
	private Article article;
	private Tenue tenue;
	private int quantite;

	public TenueArticle() {
	}

	public TenueArticle(TenueArticleId id, Article article, Tenue tenue, int quantite) {
		this.id = id;
		this.article = article;
		this.tenue = tenue;
		this.quantite = quantite;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idArticle", column = @Column(name = "id_article", nullable = false, length = 100)),
			@AttributeOverride(name = "idTenue", column = @Column(name = "id_tenue", nullable = false, length = 100)) })
	public TenueArticleId getId() {
		return this.id;
	}

	public void setId(TenueArticleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_article", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tenue", nullable = false, insertable = false, updatable = false)
	public Tenue getTenue() {
		return this.tenue;
	}

	public void setTenue(Tenue tenue) {
		this.tenue = tenue;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

}
