package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tenue generated by hbm2java
 */
@Entity
@Table(name = "tenue", catalog = "bankelmaghrib")
public class Tenue implements java.io.Serializable {

	private String intitule;
	private Set<TenueArticle> tenueArticles = new HashSet<TenueArticle>(0);
	private Set<Poste> postes = new HashSet<Poste>(0);

	public Tenue() {
	}

	public Tenue(String intitule) {
		this.intitule = intitule;
	}

	public Tenue(String intitule, Set<TenueArticle> tenueArticles, Set<Poste> postes) {
		this.intitule = intitule;
		this.tenueArticles = tenueArticles;
		this.postes = postes;
	}

	@Id

	@Column(name = "intitule", unique = true, nullable = false, length = 100)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tenue")
	public Set<TenueArticle> getTenueArticles() {
		return this.tenueArticles;
	}

	public void setTenueArticles(Set<TenueArticle> tenueArticles) {
		this.tenueArticles = tenueArticles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tenue")
	public Set<Poste> getPostes() {
		return this.postes;
	}

	public void setPostes(Set<Poste> postes) {
		this.postes = postes;
	}

}
