package entities;
// Generated Aug 26, 2016 11:30:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TenueArticleId generated by hbm2java
 */
@Embeddable
public class TenueArticleId implements java.io.Serializable {

	private String idArticle;
	private String idTenue;

	public TenueArticleId() {
	}

	public TenueArticleId(String idArticle, String idTenue) {
		this.idArticle = idArticle;
		this.idTenue = idTenue;
	}

	@Column(name = "id_article", nullable = false, length = 100)
	public String getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(String idArticle) {
		this.idArticle = idArticle;
	}

	@Column(name = "id_tenue", nullable = false, length = 100)
	public String getIdTenue() {
		return this.idTenue;
	}

	public void setIdTenue(String idTenue) {
		this.idTenue = idTenue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TenueArticleId))
			return false;
		TenueArticleId castOther = (TenueArticleId) other;

		return ((this.getIdArticle() == castOther.getIdArticle()) || (this.getIdArticle() != null
				&& castOther.getIdArticle() != null && this.getIdArticle().equals(castOther.getIdArticle())))
				&& ((this.getIdTenue() == castOther.getIdTenue()) || (this.getIdTenue() != null
						&& castOther.getIdTenue() != null && this.getIdTenue().equals(castOther.getIdTenue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdArticle() == null ? 0 : this.getIdArticle().hashCode());
		result = 37 * result + (getIdTenue() == null ? 0 : this.getIdTenue().hashCode());
		return result;
	}

}
